local colors = {
	{ name = "Black", colorindex = 0 },
	{ name = "Carbon Black", colorindex = 147 },
	{ name = "Hraphite", colorindex = 1 },
	{ name = "Anhracite Black", colorindex = 11 },
	{ name = "Black Steel", colorindex = 2 },
	{ name = "Dark Steel", colorindex = 3 },
	{ name = "Silver", colorindex = 4 },
	{ name = "Bluish Silver", colorindex = 5 },
	{ name = "Rolled Steel", colorindex = 6 },
	{ name = "Shadow Silver", colorindex = 7 },
	{ name = "Stone Silver", colorindex = 8 },
	{ name = "Midnight Silver", colorindex = 9 },
	{ name = "Cast Iron Silver", colorindex = 10 },
	{ name = "Red", colorindex = 27 },
	{ name = "Torino Red", colorindex = 28 },
	{ name = "Formula Red", colorindex = 29 },
	{ name = "Lava Red", colorindex = 150 },
	{ name = "Blaze Red", colorindex = 30 },
	{ name = "Grace Red", colorindex = 31 },
	{ name = "Garnet Red", colorindex = 32 },
	{ name = "Sunset Red", colorindex = 33 },
	{ name = "Cabernet Red", colorindex = 34 },
	{ name = "Wine Red", colorindex = 143 },
	{ name = "Candy Red", colorindex = 35 },
	{ name = "Hot Pink", colorindex = 135 },
	{ name = "Pfsiter Pink", colorindex = 137 },
	{ name = "Salmon Pink", colorindex = 136 },
	{ name = "Sunrise Orange", colorindex = 36 },
	{ name = "Orange", colorindex = 38 },
	{ name = "Bright Orange", colorindex = 138 },
	{ name = "Gold", colorindex = 99 },
	{ name = "Bronze", colorindex = 90 },
	{ name = "Yellow", colorindex = 88 },
	{ name = "Race Yellow", colorindex = 89 },
	{ name = "Dew Yellow", colorindex = 91 },
	{ name = "Dark Green", colorindex = 49 },
	{ name = "Racing Green", colorindex = 50 },
	{ name = "Sea Green", colorindex = 51 },
	{ name = "Olive Green", colorindex = 52 },
	{ name = "Bright Green", colorindex = 53 },
	{ name = "Gasoline Green", colorindex = 54 },
	{ name = "Lime Green", colorindex = 92 },
	{ name = "Midnight Blue", colorindex = 141 },
	{ name = "Galaxy Blue", colorindex = 61 },
	{ name = "Dark Blue", colorindex = 62 },
	{ name = "Saxon Blue", colorindex = 63 },
	{ name = "Blue", colorindex = 64 },
	{ name = "Mariner Blue", colorindex = 65 },
	{ name = "Harbor Blue", colorindex = 66 },
	{ name = "Diamond Blue", colorindex = 67 },
	{ name = "Surf Blue", colorindex = 68 },
	{ name = "Nautical Blue", colorindex = 69 },
	{ name = "Racing Blue", colorindex = 73 },
	{ name = "Ultra Blue", colorindex = 70 },
	{ name = "Light Blue", colorindex = 74 },
	{ name = "Chocolate Brown", colorindex = 96 },
	{ name = "Bison Brown", colorindex = 101 },
	{ name = "Creeen Brown", colorindex = 95 },
	{ name = "Feltzer Brown", colorindex = 94 },
	{ name = "Maple Brown", colorindex = 97 },
	{ name = "Beechwood Brown", colorindex = 103 },
	{ name = "Sienna Brown", colorindex = 104 },
	{ name = "Saddle Brown", colorindex = 98 },
	{ name = "Moss Brown", colorindex = 100 },
	{ name = "Woodbeech Brown", colorindex = 102 },
	{ name = "Straw Brown", colorindex = 99 },
	{ name = "Sandy Brown", colorindex = 105 },
	{ name = "Bleached Brown", colorindex = 106 },
	{ name = "Schafter Purple", colorindex = 71 },
	{ name = "Spinnaker Purple", colorindex = 72 },
	{ name = "Midnight Purple", colorindex = 142 },
	{ name = "Bright Purple", colorindex = 145 },
	{ name = "Cream", colorindex = 107 },
	{ name = "Ice White", colorindex = 111 },
	{ name = "Frost White", colorindex = 112 }
	{ name = "Brushed Steel", colorindex = 117 },
	{ name = "Brushed Black Steel", colorindex = 118 },
	{ name = "Brushed Aluminum", colorindex = 119 },
	{ name = "Pure Gold", colorindex = 158 },
	{ name = "Brushed Gold", colorindex = 159 }
	{ name = "Black", colorindex = 12 },
	{ name = "Gray", colorindex = 13 },
	{ name = "Light Gray", colorindex = 14 },
	{ name = "Ice White", colorindex = 131 },
	{ name = "Blue", colorindex = 83 },
	{ name = "Dark Blue", colorindex = 82 },
	{ name = "Midnight Blue", colorindex = 84 },
	{ name = "Midnight Purple", colorindex = 149 },
	{ name = "Schafter Purple", colorindex = 148 },
	{ name = "Red", colorindex = 39 },
	{ name = "Dark Red", colorindex = 40 },
	{ name = "Orange", colorindex = 41 },
	{ name = "Yellow", colorindex = 42 },
	{ name = "Lime Green", colorindex = 55 },
	{ name = "Green", colorindex = 128 },
	{ name = "Frost Green", colorindex = 151 },
	{ name = "Foliage Green", colorindex = 155 },
	{ name = "Olive Darb", colorindex = 152 },
	{ name = "Dark Earth", colorindex = 153 },
	{ name = "Desert Tan", colorindex = 154 }
}


-----------------------------------------------------------------------------------------------------------------------------------------
-- GET VEH LIST FROM VRP/CLIENT/BASIC_GARAGE
------------------------------------------------------------------------------------------------------------------------------------------
local vehglobal = {
	["blista"] = { ['name'] = "Blista", ['price'] = 80000, ['tipo'] = "carros" },
	["brioso"] = { ['name'] = "Brioso", ['price'] = 35000, ['tipo'] = "carros" },
	["emperor"] = { ['name'] = "Emperor", ['price'] = 55000, ['tipo'] = "carros" },
	["emperor2"] = { ['name'] = "Emperor 2", ['price'] = 40000, ['tipo'] = "carros" },
	["dilettante"] = { ['name'] = "Dilettante", ['price'] = 40000, ['tipo'] = "carros" },
	["issi2"] = { ['name'] = "Issi2", ['price'] = 90000, ['tipo'] = "carros" },
	["panto"] = { ['name'] = "Panto", ['price'] = 8000, ['tipo'] = "carros" },
	["prairie"] = { ['name'] = "Prairie", ['price'] = 25000, ['tipo'] = "carros" },
	["rhapsody"] = { ['name'] = "Rhapsody", ['price'] = 10000, ['tipo'] = "carros" },
	["cogcabrio"] = { ['name'] = "Cogcabrio", ['price'] = 400000, ['tipo'] = "carros" },
	["exemplar"] = { ['name'] = "Exemplar", ['price'] = 80000, ['tipo'] = "carros" },
	["f620"] = { ['name'] = "F620", ['price'] = 55000, ['tipo'] = "carros" },
	["felon"] = { ['name'] = "Felon", ['price'] = 70000, ['tipo'] = "carros" },
	["ingot"] = { ['name'] = "Ingot", ['price'] = 90000, ['tipo'] = "carros" },
	["jackal"] = { ['name'] = "Jackal", ['price'] = 60000, ['tipo'] = "carros" },
	["oracle"] = { ['name'] = "Oracle", ['price'] = 70000, ['tipo'] = "carros" },
	["oracle2"] = { ['name'] = "Oracle2", ['price'] = 80000, ['tipo'] = "carros" },
	["sentinel"] = { ['name'] = "Sentinel", ['price'] = 14000, ['tipo'] = "carros" },
	["sentinel2"] = { ['name'] = "Sentinel2", ['price'] = 50000, ['tipo'] = "carros" },
	["windsor"] = { ['name'] = "Windsor", ['price'] = 150000, ['tipo'] = "carros" },
	["windsor2"] = { ['name'] = "Windsor2", ['price'] = 200000, ['tipo'] = "carros" },
	["zion"] = { ['name'] = "Zion", ['price'] = 80000, ['tipo'] = "carros" },
	["zion2"] = { ['name'] = "Zion2", ['price'] = 85000, ['tipo'] = "carros" },
	["blade"] = { ['name'] = "Blade", ['price'] = 110000, ['tipo'] = "carros" },
	["buccaneer"] = { ['name'] = "Buccaneer", ['price'] = 130000, ['tipo'] = "carros" },
	["buccaneer2"] = { ['name'] = "Buccaneer2", ['price'] = 200000, ['tipo'] = "carros" },
	["primo"] = { ['name'] = "Primo", ['price'] = 40000, ['tipo'] = "carros" },
	["chino"] = { ['name'] = "Chino", ['price'] = 130000, ['tipo'] = "carros" },
	["coquette3"] = { ['name'] = "Coquette3", ['price'] = 195000, ['tipo'] = "carros" },
	["dukes"] = { ['name'] = "Dukes", ['price'] = 180000, ['tipo'] = "carros" },
	["faction"] = { ['name'] = "Faction", ['price'] = 150000, ['tipo'] = "carros" },
	["faction3"] = { ['name'] = "Faction3", ['price'] = 350000, ['tipo'] = "carros" },
	["gauntlet"] = { ['name'] = "Gauntlet", ['price'] = 165000, ['tipo'] = "carros" },
	["gauntlet2"] = { ['name'] = "Gauntlet2", ['price'] = 165000, ['tipo'] = "carros" },
	["hermes"] = { ['name'] = "Hermes", ['price'] = 280000, ['tipo'] = "carros" },
	["hotknife"] = { ['name'] = "Hotknife", ['price'] = 180000, ['tipo'] = "carros" },
	["moonbeam"] = { ['name'] = "Moonbeam", ['price'] = 220000, ['tipo'] = "carros" },
	["moonbeam2"] = { ['name'] = "Moonbeam2", ['price'] = 250000, ['tipo'] = "carros" },
	["nightshade"] = { ['name'] = "Nightshade", ['price'] = 270000, ['tipo'] = "carros" },
	["picador"] = { ['name'] = "Picador", ['price'] = 150000, ['tipo'] = "carros" },
	["ruiner"] = { ['name'] = "Ruiner", ['price'] = 320000, ['tipo'] = "carros" },
	["sabregt"] = { ['name'] = "Sabregt", ['price'] = 350000, ['tipo'] = "carros" },
	["sabregt2"] = { ['name'] = "Sabregt2", ['price'] = 400000, ['tipo'] = "carros" },
	["slamvan"] = { ['name'] = "Slamvan", ['price'] = 100000, ['tipo'] = "carros" },
	["slamvan3"] = { ['name'] = "Slamvan3", ['price'] = 150000, ['tipo'] = "carros" },
	["stalion"] = { ['name'] = "Stalion", ['price'] = 150000, ['tipo'] = "carros" },
	["stalion2"] = { ['name'] = "Stalion2", ['price'] = 150000, ['tipo'] = "carros" },
	["tampa"] = { ['name'] = "Tampa", ['price'] = 220000, ['tipo'] = "carros" },
	["vigero"] = { ['name'] = "Vigero", ['price'] = 170000, ['tipo'] = "carros" },
	["virgo"] = { ['name'] = "Virgo", ['price'] = 130000, ['tipo'] = "carros" },
	["virgo2"] = { ['name'] = "Virgo2", ['price'] = 150000, ['tipo'] = "carros" },
	["virgo3"] = { ['name'] = "Virgo3", ['price'] = 180000, ['tipo'] = "carros" },
	["voodoo"] = { ['name'] = "Voodoo", ['price'] = 190000, ['tipo'] = "carros" },
	["voodoo2"] = { ['name'] = "Voodoo2", ['price'] = 100000, ['tipo'] = "carros" },
	["yosemite"] = { ['name'] = "Yosemite", ['price'] = 350000, ['tipo'] = "carros" },
	["bfinjection"] = { ['name'] = "Bfinjection", ['price'] = 80000, ['tipo'] = "carros" },
	["bifta"] = { ['name'] = "Bifta", ['price'] = 190000, ['tipo'] = "carros" },
	["bodhi2"] = { ['name'] = "Bodhi2", ['price'] = 170000, ['tipo'] = "carros" },
	["brawler"] = { ['name'] = "Brawler", ['price'] = 250000, ['tipo'] = "carros" },
	["trophytruck"] = { ['name'] = "Trophytruck", ['price'] = 400000, ['tipo'] = "carros" },
	["trophytruck2"] = { ['name'] = "Trophytruck2", ['price'] = 400000, ['tipo'] = "carros" },
	["dubsta3"] = { ['name'] = "Dubsta3", ['price'] = 470000, ['tipo'] = "carros" },
	["mesa3"] = { ['name'] = "Mesa3", ['price'] = 200000, ['tipo'] = "carros" },
	["rancherxl"] = { ['name'] = "Rancherxl", ['price'] = 250000, ['tipo'] = "carros" },
	["rebel2"] = { ['name'] = "Rebel2", ['price'] = 250000, ['tipo'] = "carros" },
	["riata"] = { ['name'] = "Riata", ['price'] = 250000, ['tipo'] = "carros" },
	["dloader"] = { ['name'] = "Dloader", ['price'] = 150000, ['tipo'] = "carros" },
	["sandking"] = { ['name'] = "Sandking", ['price'] = 400000, ['tipo'] = "carros" },
	["sandking2"] = { ['name'] = "Sandking2", ['price'] = 350000, ['tipo'] = "carros" },
	["baller"] = { ['name'] = "Baller", ['price'] = 150000, ['tipo'] = "carros" },
	["baller2"] = { ['name'] = "Baller2", ['price'] = 150000, ['tipo'] = "carros" },
	["baller3"] = { ['name'] = "Baller3", ['price'] = 155000, ['tipo'] = "carros" },
	["baller4"] = { ['name'] = "Baller4", ['price'] = 185000, ['tipo'] = "carros" },
	["baller5"] = { ['name'] = "Baller5", ['price'] = 1000000, ['tipo'] = "carros" },
	["baller6"] = { ['name'] = "Baller6", ['price'] = 1200000, ['tipo'] = "carros" },
	["bjxl"] = { ['name'] = "Bjxl", ['price'] = 200000, ['tipo'] = "carros" },
	["cavalcade"] = { ['name'] = "Cavalcade", ['price'] = 110000, ['tipo'] = "carros" },
	["cavalcade2"] = { ['name'] = "Cavalcade2", ['price'] = 150000, ['tipo'] = "carros" },
	["contender"] = { ['name'] = "Contender", ['price'] = 550000, ['tipo'] = "carros" },
	["dubsta"] = { ['name'] = "Dubsta", ['price'] = 250000, ['tipo'] = "carros" },
	["dubsta2"] = { ['name'] = "Dubsta2", ['price'] = 350000, ['tipo'] = "carros" },
	["fq2"] = { ['name'] = "Fq2", ['price'] = 110000, ['tipo'] = "carros" },
	["granger"] = { ['name'] = "Granger", ['price'] = 345000, ['tipo'] = "carros" },
	["gresley"] = { ['name'] = "Gresley", ['price'] = 150000, ['tipo'] = "carros" },
	["habanero"] = { ['name'] = "Habanero", ['price'] = 100000, ['tipo'] = "carros" },
	["seminole"] = { ['name'] = "Seminole", ['price'] = 250000, ['tipo'] = "carros" },
	["serrano"] = { ['name'] = "Serrano", ['price'] = 120000, ['tipo'] = "carros" },
	["xls"] = { ['name'] = "Xls", ['price'] = 170000, ['tipo'] = "carros" },
	["xls2"] = { ['name'] = "Xls2", ['price'] = 300000, ['tipo'] = "carros" },
	["asea"] = { ['name'] = "Asea", ['price'] = 35000, ['tipo'] = "carros" },
	["asterope"] = { ['name'] = "Asterope", ['price'] = 50000, ['tipo'] = "carros" },
	["cog552"] = { ['name'] = "Cog552", ['price'] = 850000, ['tipo'] = "carros" },
	["cognoscenti"] = { ['name'] = "Cognoscenti", ['price'] = 250000, ['tipo'] = "carros" },
	["cognoscenti2"] = { ['name'] = "Cognoscenti2", ['price'] = 850000, ['tipo'] = "carros" },
	["stanier"] = { ['name'] = "Stanier", ['price'] = 55000, ['tipo'] = "carros" },
	["stratum"] = { ['name'] = "Stratum", ['price'] = 75000, ['tipo'] = "carros" },
	["surge"] = { ['name'] = "Surge", ['price'] = 230000, ['tipo'] = "carros" },
	["tailgater"] = { ['name'] = "Tailgater", ['price'] = 110000, ['tipo'] = "carros" },
	["warrener"] = { ['name'] = "Warrener", ['price'] = 90000, ['tipo'] = "carros" },
	["washington"] = { ['name'] = "Washington", ['price'] = 90000, ['tipo'] = "carros" },
	["alpha"] = { ['name'] = "Alpha", ['price'] = 310000, ['tipo'] = "carros" },
	["banshee"] = { ['name'] = "Banshee", ['price'] = 380000, ['tipo'] = "carros" },
	["bestiagts"] = { ['name'] = "Bestiagts", ['price'] = 320000, ['tipo'] = "carros" },
	["blista2"] = { ['name'] = "Blista2", ['price'] = 55000, ['tipo'] = "carros" },
	["blista3"] = { ['name'] = "Blista3", ['price'] = 110000, ['tipo'] = "carros" },
	["buffalo"] = { ['name'] = "Buffalo", ['price'] = 200000, ['tipo'] = "carros" },
	["buffalo3"] = { ['name'] = "Buffalo3", ['price'] = 300000, ['tipo'] = "carros" },
	["carbonizzare"] = { ['name'] = "Carbonizzare", ['price'] = 390000, ['tipo'] = "carros" },
	["comet2"] = { ['name'] = "Comet2", ['price'] = 310000, ['tipo'] = "carros" },
	["comet3"] = { ['name'] = "Comet3", ['price'] = 380000, ['tipo'] = "carros" },
	["comet5"] = { ['name'] = "Comet5", ['price'] = 400000, ['tipo'] = "carros" },
	["coquette"] = { ['name'] = "Coquette", ['price'] = 500000, ['tipo'] = "carros" },
	["elegy"] = { ['name'] = "Elegy", ['price'] = 350000, ['tipo'] = "carros" },
	["elegy2"] = { ['name'] = "Elegy2", ['price'] = 450000, ['tipo'] = "carros" },
	["feltzer2"] = { ['name'] = "Feltzer2", ['price'] = 450000, ['tipo'] = "carros" },
	["furoregt"] = { ['name'] = "Furoregt", ['price'] = 310000, ['tipo'] = "carros" },
	["fusilade"] = { ['name'] = "Fusilade", ['price'] = 210000, ['tipo'] = "carros" },
	["futo"] = { ['name'] = "Futo", ['price'] = 110000, ['tipo'] = "carros" },
	["jester"] = { ['name'] = "Jester", ['price'] = 950000, ['tipo'] = "carros" },
	["khamelion"] = { ['name'] = "Khamelion", ['price'] = 350000, ['tipo'] = "carros" },
	["kuruma"] = { ['name'] = "Kuruma", ['price'] = 500000, ['tipo'] = "carros" },
	["massacro"] = { ['name'] = "Massacro", ['price'] = 350000, ['tipo'] = "carros" },
	["massacro2"] = { ['name'] = "Massacro2", ['price'] = 400000, ['tipo'] = "carros" },
	["ninef"] = { ['name'] = "Ninef", ['price'] = 500000, ['tipo'] = "carros" },
	["ninef2"] = { ['name'] = "Ninef2", ['price'] = 520000, ['tipo'] = "carros" },
	["omnis"] = { ['name'] = "Omnis", ['price'] = 240000, ['tipo'] = "carros" },
	["pariah"] = { ['name'] = "Pariah", ['price'] = 620000, ['tipo'] = "carros" },
	["penumbra"] = { ['name'] = "Penumbra", ['price'] = 200000, ['tipo'] = "carros" },
	["raiden"] = { ['name'] = "Raiden", ['price'] = 450000, ['tipo'] = "carros" },
	["rapidgt"] = { ['name'] = "Rapidgt", ['price'] = 400000, ['tipo'] = "carros" },
	["rapidgt2"] = { ['name'] = "Rapidgt2", ['price'] = 450000, ['tipo'] = "carros" },
	["ruston"] = { ['name'] = "Ruston", ['price'] = 350000, ['tipo'] = "carros" },
	["schafter3"] = { ['name'] = "Schafter3", ['price'] = 270000, ['tipo'] = "carros" },
	["schafter5"] = { ['name'] = "Schafter5", ['price'] = 255000, ['tipo'] = "carros" },
	["schwarzer"] = { ['name'] = "Schwarzer", ['price'] = 200000, ['tipo'] = "carros" },
	["sentinel3"] = { ['name'] = "Sentinel3", ['price'] = 75000, ['tipo'] = "carros" },
	["seven70"] = { ['name'] = "Seven70", ['price'] = 570000, ['tipo'] = "carros" },
	["specter"] = { ['name'] = "Specter", ['price'] = 300000, ['tipo'] = "carros" },
	["specter2"] = { ['name'] = "Specter2", ['price'] = 330000, ['tipo'] = "carros" },
	["streiter"] = { ['name'] = "Streiter", ['price'] = 250000, ['tipo'] = "carros" },
	["sultan"] = { ['name'] = "Sultan", ['price'] = 430000, ['tipo'] = "carros" },
	["surano"] = { ['name'] = "Surano", ['price'] = 360000, ['tipo'] = "carros" },
	["tampa2"] = { ['name'] = "Tampa2", ['price'] = 250000, ['tipo'] = "carros" },
	["tropos"] = { ['name'] = "Tropos", ['price'] = 250000, ['tipo'] = "carros" },
	["verlierer2"] = { ['name'] = "Verlierer2", ['price'] = 200000, ['tipo'] = "carros" },
	["btype2"] = { ['name'] = "Btype2", ['price'] = 460000, ['tipo'] = "carros" },
	["btype3"] = { ['name'] = "Btype3", ['price'] = 485000, ['tipo'] = "carros" },
	["casco"] = { ['name'] = "Casco", ['price'] = 200000, ['tipo'] = "carros" },
	["cheetah"] = { ['name'] = "Cheetah", ['price'] = 425000, ['tipo'] = "carros" },
	["coquette2"] = { ['name'] = "Coquette2", ['price'] = 200000, ['tipo'] = "carros" },
	["feltzer3"] = { ['name'] = "Feltzer3", ['price'] = 220000, ['tipo'] = "carros" },
	["gt500"] = { ['name'] = "Gt500", ['price'] = 350000, ['tipo'] = "carros" },
	["infernus2"] = { ['name'] = "Infernus2", ['price'] = 350000, ['tipo'] = "carros" },
	["jb700"] = { ['name'] = "Jb700", ['price'] = 260000, ['tipo'] = "carros" },
	["mamba"] = { ['name'] = "Mamba", ['price'] = 1200000, ['tipo'] = "carros" },
	["manana"] = { ['name'] = "Manana", ['price'] = 130000, ['tipo'] = "carros" },
	["monroe"] = { ['name'] = "Monroe", ['price'] = 230000, ['tipo'] = "carros" },
	["peyote"] = { ['name'] = "Peyote", ['price'] = 150000, ['tipo'] = "carros" },
	["pigalle"] = { ['name'] = "Pigalle", ['price'] = 150000, ['tipo'] = "carros" },
	["rapidgt3"] = { ['name'] = "Rapidgt3", ['price'] = 300000, ['tipo'] = "carros" },
	["retinue"] = { ['name'] = "Retinue", ['price'] = 200000, ['tipo'] = "carros" },
	["stinger"] = { ['name'] = "Stinger", ['price'] = 210000, ['tipo'] = "carros" },
	["stingergt"] = { ['name'] = "Stingergt", ['price'] = 230000, ['tipo'] = "carros" },
	["torero"] = { ['name'] = "Torero", ['price'] = 160000, ['tipo'] = "carros" },
	["tornado"] = { ['name'] = "Tornado", ['price'] = 250000, ['tipo'] = "carros" },
	["tornado2"] = { ['name'] = "Tornado2", ['price'] = 160000, ['tipo'] = "carros" },
	["tornado6"] = { ['name'] = "Tornado6", ['price'] = 250000, ['tipo'] = "carros" },
	["turismo2"] = { ['name'] = "Turismo2", ['price'] = 290000, ['tipo'] = "carros" },
	["ztype"] = { ['name'] = "Ztype", ['price'] = 500000, ['tipo'] = "carros" },
	["adder"] = { ['name'] = "Adder", ['price'] = 620000, ['tipo'] = "carros" },
	["autarch"] = { ['name'] = "Autarch", ['price'] = 760000, ['tipo'] = "carros" },
	["banshee2"] = { ['name'] = "Banshee2", ['price'] = 430000, ['tipo'] = "carros" },
	["bullet"] = { ['name'] = "Bullet", ['price'] = 420000, ['tipo'] = "carros" },
	["cheetah2"] = { ['name'] = "Cheetah2", ['price'] = 240000, ['tipo'] = "carros" },
	["entityxf"] = { ['name'] = "Entityxf", ['price'] = 850000, ['tipo'] = "carros" },
	["fmj"] = { ['name'] = "Fmj", ['price'] = 900000, ['tipo'] = "carros" },
	["gp1"] = { ['name'] = "Gp1", ['price'] = 659000, ['tipo'] = "carros" },
	["infernus"] = { ['name'] = "Infernus", ['price'] = 650000, ['tipo'] = "carros" },
	["nero"] = { ['name'] = "Nero", ['price'] = 750000, ['tipo'] = "carros" },
	["nero2"] = { ['name'] = "Nero2", ['price'] = 850000, ['tipo'] = "carros" },
	["osiris"] = { ['name'] = "Osiris", ['price'] = 1600000, ['tipo'] = "carros" },
	["penetrator"] = { ['name'] = "Penetrator", ['price'] = 1080000, ['tipo'] = "carros" },
	["pfister811"] = { ['name'] = "Pfister811", ['price'] = 830000, ['tipo'] = "carros" },
	["reaper"] = { ['name'] = "Reaper", ['price'] = 630000, ['tipo'] = "carros" },
	["sc1"] = { ['name'] = "Sc1", ['price'] = 500000, ['tipo'] = "carros" },
	["sultanrs"] = { ['name'] = "Sultan RS", ['price'] = 500000, ['tipo'] = "carros" },
	["t20"] = { ['name'] = "T20", ['price'] = 670000, ['tipo'] = "carros" },
	["tempesta"] = { ['name'] = "Tempesta", ['price'] = 650000, ['tipo'] = "carros" },
	["turismor"] = { ['name'] = "Turismor", ['price'] = 600000, ['tipo'] = "carros" },
	["tyrus"] = { ['name'] = "Tyrus", ['price'] = 1200000, ['tipo'] = "carros" },
	["vacca"] = { ['name'] = "Vacca", ['price'] = 620000, ['tipo'] = "carros" },
	["visione"] = { ['name'] = "Visione", ['price'] = 790000, ['tipo'] = "carros" },
	["voltic"] = { ['name'] = "Voltic", ['price'] = 440000, ['tipo'] = "carros" },
	["zentorno"] = { ['name'] = "Zentorno", ['price'] = 920000, ['tipo'] = "carros" },
	["sadler"] = { ['name'] = "Sadler", ['price'] = 300000, ['tipo'] = "carros" },
	["bison"] = { ['name'] = "Bison", ['price'] = 400000, ['tipo'] = "carros" },
	["bison2"] = { ['name'] = "Bison2", ['price'] = 430000, ['tipo'] = "carros" },
    ["bobcatxl"] = { ['name'] = "Bobcatxl", ['price'] = 260000, ['tipo'] = "carros" },
	["burrito3"] = { ['name'] = "Burrito3", ['price'] = 260000, ['tipo'] = "carros" },
	["mule4"] = { ['name'] = "Mule4", ['price'] = 900000, ['tipo'] = "carros" },
	["rallytruck"] = { ['name'] = "RallyTruck", ['price'] = 1800000, ['tipo'] = "carros" },
	["minivan"] = { ['name'] = "Minivan", ['price'] = 110000, ['tipo'] = "carros" },
	["minivan2"] = { ['name'] = "Minivan2", ['price'] = 220000, ['tipo'] = "carros" },
	["paradise"] = { ['name'] = "Paradise", ['price'] = 460000, ['tipo'] = "carros" },
	["pony"] = { ['name'] = "Pony", ['price'] = 490000, ['tipo'] = "carros" },
	["pony2"] = { ['name'] = "Pony2", ['price'] = 500000, ['tipo'] = "carros" },
	["rumpo"] = { ['name'] = "Rumpo", ['price'] = 460000, ['tipo'] = "carros" },
	["rumpo3"] = { ['name'] = "Rumpo3", ['price'] = 650000, ['tipo'] = "carros" },
	["surfer"] = { ['name'] = "Surfer", ['price'] = 600000, ['tipo'] = "carros" },
	["huntley"] = { ['name'] = "Huntley", ['price'] = 310000, ['tipo'] = "carros" },
	["landstalker"] = { ['name'] = "Landstalker", ['price'] = 230000, ['tipo'] = "carros" },
	["mesa"] = { ['name'] = "Mesa", ['price'] = 190000, ['tipo'] = "carros" },
	["patriot"] = { ['name'] = "Patriot", ['price'] = 350000, ['tipo'] = "carros" },
	["radi"] = { ['name'] = "Radi", ['price'] = 100000, ['tipo'] = "carros" },
	["rocoto"] = { ['name'] = "Rocoto", ['price'] = 210000, ['tipo'] = "carros" },
	["tyrant"] = { ['name'] = "Tyrant", ['price'] = 700000, ['tipo'] = "carros" },
	["entity2"] = { ['name'] = "Entity2", ['price'] = 1000000, ['tipo'] = "carros" },
	["cheburek"] = { ['name'] = "Cheburek", ['price'] = 70000, ['tipo'] = "carros" },
	["hotring"] = { ['name'] = "Hotring", ['price'] = 210000, ['tipo'] = "carros" },
	["jester3"] = { ['name'] = "Jester3", ['price'] = 545000, ['tipo'] = "carros" },
	["flashgt"] = { ['name'] = "Flashgt", ['price'] = 470000, ['tipo'] = "carros" },
	["ellie"] = { ['name'] = "Ellie", ['price'] = 300000, ['tipo'] = "carros" },
	["michelli"] = { ['name'] = "Michelli", ['price'] = 100000, ['tipo'] = "carros" },
	["fagaloa"] = { ['name'] = "Fagaloa", ['price'] = 120000, ['tipo'] = "carros" },
	["dominator"] = { ['name'] = "Dominator", ['price'] = 300000, ['tipo'] = "carros" },
	["dominator2"] = { ['name'] = "Dominator2", ['price'] = 500000, ['tipo'] = "carros" },
	["dominator3"] = { ['name'] = "Dominator3", ['price'] = 1250000, ['tipo'] = "carros" },
	["issi3"] = { ['name'] = "Issi3", ['price'] = 190000, ['tipo'] = "carros" },
	["taipan"] = { ['name'] = "Taipan", ['price'] = 620000, ['tipo'] = "carros" },
	["gb200"] = { ['name'] = "Gb200", ['price'] = 295000, ['tipo'] = "carros" },
	["stretch"] = { ['name'] = "Stretch", ['price'] = 1520000, ['tipo'] = "carros" },
	["guardian"] = { ['name'] = "Guardian", ['price'] = 640000, ['tipo'] = "carros" },
	["kamacho"] = { ['name'] = "Kamacho", ['price'] = 460000, ['tipo'] = "carros" },
	["neon"] = { ['name'] = "Neon", ['price'] = 700000, ['tipo'] = "carros" },
	["cyclone"] = { ['name'] = "Cyclone", ['price'] = 1220000, ['tipo'] = "carros" },
	["italigtb"] = { ['name'] = "Italigtb", ['price'] = 1000000, ['tipo'] = "carros" },
	["italigtb2"] = { ['name'] = "Italigtb2", ['price'] = 1200000, ['tipo'] = "carros" },
	["vagner"] = { ['name'] = "Vagner", ['price'] = 780000, ['tipo'] = "carros" },
	["xa21"] = { ['name'] = "Xa21", ['price'] = 1330000, ['tipo'] = "carros" },
	["tezeract"] = { ['name'] = "Tezeract", ['price'] = 920000, ['tipo'] = "carros" },
	["prototipo"] = { ['name'] = "Prototipo", ['price'] = 800000, ['tipo'] = "carros" },
	["patriot2"] = { ['name'] = "Patriot2", ['price'] = 1050000, ['tipo'] = "carros" },
	["swinger"] = { ['name'] = "Swinger", ['price'] = 1050000, ['tipo'] = "carros" },
	["clique"] = { ['name'] = "Clique", ['price'] = 30000, ['tipo'] = "carros" },
	["deveste"] = { ['name'] = "Deveste", ['price'] = 1250000, ['tipo'] = "carros" },
	["deviant"] = { ['name'] = "Deviant", ['price'] = 770000, ['tipo'] = "carros" },
	["impaler"] = { ['name'] = "Impaler", ['price'] = 820000, ['tipo'] = "carros" },
	["italigto"] = { ['name'] = "Italigto", ['price'] = 1000000, ['tipo'] = "carros" },
	["schlagen"] = { ['name'] = "Schlagen", ['price'] = 700000, ['tipo'] = "carros" },
	["toros"] = { ['name'] = "Toros", ['price'] = 520000, ['tipo'] = "carros" },
	["tulip"] = { ['name'] = "Tulip", ['price'] = 320000, ['tipo'] = "carros" },
	["vamos"] = { ['name'] = "Vamos", ['price'] = 320000, ['tipo'] = "carros" },
	["freecrawler"] = { ['name'] = "Freecrawler", ['price'] = 650000, ['tipo'] = "carros" },
	["fugitive"] = { ['name'] = "Fugitive", ['price'] = 250000, ['tipo'] = "carros" },
	["glendale"] = { ['name'] = "Glendale", ['price'] = 90000, ['tipo'] = "carros" },
	["intruder"] = { ['name'] = "Intruder", ['price'] = 60000, ['tipo'] = "carros" },
	["le7b"] = { ['name'] = "Le7b", ['price'] = 700000, ['tipo'] = "carros" },
	["lurcher"] = { ['name'] = "Lurcher", ['price'] = 150000, ['tipo'] = "carros" },
	["lynx"] = { ['name'] = "Lynx", ['price'] = 970000, ['tipo'] = "carros" },
	["phoenix"] = { ['name'] = "Phoenix", ['price'] = 500000, ['tipo'] = "carros" },
	["premier"] = { ['name'] = "Premier", ['price'] = 50000, ['tipo'] = "carros" },
	["raptor"] = { ['name'] = "Raptor", ['price'] = 400000, ['tipo'] = "carros" },
	["sheava"] = { ['name'] = "Sheava", ['price'] = 500000, ['tipo'] = "carros" },
	["z190"] = { ['name'] = "Z190", ['price'] = 350000, ['tipo'] = "carros" },
	["freecrawler"] = { ['name'] = "Freecrawler", ['price'] = 300000, ['tipo'] = "carros" },
	["type263"] = { ['name'] = "Kombi 63", ['price'] = 500000, ['tipo'] = "carros" },
	["beetle74"] = { ['name'] = "Fusca 74", ['price'] = 500000, ['tipo'] = "carros" },
	["fe86"] = { ['name'] = "Escorte", ['price'] = 500000, ['tipo'] = "carros" },
	["akuma"] = { ['name'] = "Akuma", ['price'] = 500000, ['tipo'] = "motos" },
	["avarus"] = { ['name'] = "Avarus", ['price'] = 440000, ['tipo'] = "motos" },
	["bagger"] = { ['name'] = "Bagger", ['price'] = 300000, ['tipo'] = "motos" },
	["bati"] = { ['name'] = "Bati", ['price'] = 370000, ['tipo'] = "motos" },
	["bati2"] = { ['name'] = "Bati2", ['price'] = 400000, ['tipo'] = "motos" },
	["bf400"] = { ['name'] = "Bf400", ['price'] = 280000, ['tipo'] = "motos" },
	["carbonrs"] = { ['name'] = "Carbonrs", ['price'] = 400000, ['tipo'] = "motos" },
	["chimera"] = { ['name'] = "Chimera", ['price'] = 340000, ['tipo'] = "motos" },
	["cliffhanger"] = { ['name'] = "Cliffhanger", ['price'] = 300000, ['tipo'] = "motos" },
	["daemon2"]  = { ['name'] = "Daemon2", ['price'] = 250000, ['tipo'] = "motos" },
	["defiler"] = { ['name'] = "Defiler", ['price'] = 390000, ['tipo'] = "motos" },
	["diablous"] = { ['name'] = "Diablous", ['price'] = 630000, ['tipo'] = "motos" },
	["diablous2"] = { ['name'] = "Diablous2", ['price'] = 660000, ['tipo'] = "motos" },
	["double"] = { ['name'] = "Double", ['price'] = 660000, ['tipo'] = "motos" },
	["enduro"] = { ['name'] = "Enduro", ['price'] = 200000, ['tipo'] = "motos" },
	["esskey"] = { ['name'] = "Esskey", ['price'] = 320000, ['tipo'] = "motos" },
	["faggio"] = { ['name'] = "Faggio", ['price'] = 4000, ['tipo'] = "motos" },
	["faggio2"] = { ['name'] = "Faggio2", ['price'] = 5000, ['tipo'] = "motos" },
	["faggio3"] = { ['name'] = "Faggio3", ['price'] = 6000, ['tipo'] = "motos" },
	["fcr"] = { ['name'] = "Fcr", ['price'] = 270000, ['tipo'] = "motos" },
	["fcr2"] = { ['name'] = "Fcr2", ['price'] = 310000, ['tipo'] = "motos" },
	["gargoyle"] = { ['name'] = "Gargoyle", ['price'] = 345000, ['tipo'] = "motos" },
	["hakuchou"] = { ['name'] = "Hakuchou", ['price'] = 700000, ['tipo'] = "motos" },
	["hakuchou2"] = { ['name'] = "Hakuchou2", ['price'] = 850000, ['tipo'] = "motos" },
	["hexer"] = { ['name'] = "Hexer", ['price'] = 250000, ['tipo'] = "motos" },
	["innovation"] = { ['name'] = "Innovation", ['price'] = 450000, ['tipo'] = "motos" },
	["lectro"] = { ['name'] = "Lectro", ['price'] = 470000, ['tipo'] = "motos" },
	["manchez"] = { ['name'] = "Manchez", ['price'] = 355000, ['tipo'] = "motos" },
	["nemesis"] = { ['name'] = "Nemesis", ['price'] = 350000, ['tipo'] = "motos" },
	["nightblade"] = { ['name'] = "Nightblade", ['price'] = 510000, ['tipo'] = "motos" },
	["pcj"] = { ['name'] = "Pcj", ['price'] = 330000, ['tipo'] = "motos" },
	["ruffian"] = { ['name'] = "Ruffian", ['price'] = 345000, ['tipo'] = "motos" },
	["sanchez"] = { ['name'] = "Sanchez", ['price'] = 185000, ['tipo'] = "motos" },
	["sanchez2"] = { ['name'] = "Sanchez2", ['price'] = 195000, ['tipo'] = "motos" },
	["sovereign"] = { ['name'] = "Sovereign", ['price'] = 385000, ['tipo'] = "motos" },
	["thrust"] = { ['name'] = "Thrust", ['price'] = 375000, ['tipo'] = "motos" },
	["vader"] = { ['name'] = "Vader", ['price'] = 345000, ['tipo'] = "motos" },
	["vindicator"] = { ['name'] = "Vindicator", ['price'] = 340000, ['tipo'] = "motos" },
	["vortex"] = { ['name'] = "Vortex", ['price'] = 315000, ['tipo'] = "motos" },
	["wolfsbane"] = { ['name'] = "Wolfsbane", ['price'] = 390000, ['tipo'] = "motos" },
	["zombiea"] = { ['name'] = "Zombiea", ['price'] = 355000, ['tipo'] = "motos" },
	["zombieb"] = { ['name'] = "Zombieb", ['price'] = 360000, ['tipo'] = "motos" },
	["shotaro"] = { ['name'] = "Shotaro", ['price'] = 1500000, ['tipo'] = "motos" },
	["ratbike"] = { ['name'] = "Ratbike", ['price'] = 230000, ['tipo'] = "motos" },
	["blazer"] = { ['name'] = "Blazer", ['price'] = 230000, ['tipo'] = "motos" },
	["blazer4"] = { ['name'] = "Blazer4", ['price'] = 370000, ['tipo'] = "motos" },
	["africat"] = { ['name'] = "Africa Twin", ['price'] = 400000, ['tipo'] = "motos" },
	["rc"] = { ['name'] = "KTM", ['price'] = 4000000, ['tipo'] = "motos" },
	["youga2"] = { ['name'] = "Youga2", ['price'] = 1000, ['tipo'] = "work" },
	["stockade"] = { ['name'] = "Stockade", ['price'] = 1000, ['tipo'] = "work" },
	["felon2"] = { ['name'] = "Felon2", ['price'] = 1000, ['tipo'] = "work" },
	["boxville2"] = { ['name'] = "Boxville2", ['price'] = 1000, ['tipo'] = "work" },
	["pbus"] = { ['name'] = "PBus", ['price'] = 1000, ['tipo'] = "work" },
	["policiacharger2018"] = { ['name'] = "Dodge Charger 2018", ['price'] = 1000, ['tipo'] = "work" },
	["policiamustanggt"] = { ['name'] = "Mustang GT", ['price'] = 1000, ['tipo'] = "work" },
	["14charger"] = { ['name'] = "2014 Charger", ['price'] = 1000, ['tipo'] = "work" },
	["18tahoe"] = { ['name'] = "2018 Tahoe", ['price'] = 1000, ['tipo'] = "work" },
	["18charger"] = { ['name'] = "2018 Charger", ['price'] = 1000, ['tipo'] = "work" },
	["19durango"] = { ['name'] = "Unidade Tatica", ['price'] = 1000, ['tipo'] = "work" },
	["chargervtr"] = { ['name'] = "Sheriff NÃO USAR", ['price'] = 1000, ['tipo'] = "work" },
	["policiacapricesid"] = { ['name'] = "GM Caprice SID", ['price'] = 1000, ['tipo'] = "work" },
	["policiaschaftersid"] = { ['name'] = "GM Schafter SID", ['price'] = 1000, ['tipo'] = "work" },
	["policiasilverado"] = { ['name'] = "Chevrolet Silverado", ['price'] = 1000, ['tipo'] = "work" },
	["policiatahoe"] = { ['name'] = "Chevrolet Tahoe", ['price'] = 1000, ['tipo'] = "work" },
	["policiaexplorer"] = { ['name'] = "Ford Explorer", ['price'] = 1000, ['tipo'] = "work" },
	["policiataurus"] = { ['name'] = "Ford Taurus", ['price'] = 1000, ['tipo'] = "work" },
	["policiavictoria"] = { ['name'] = "Ford Victoria", ['price'] = 1000, ['tipo'] = "work" },
	["pol718"] = { ['name'] = "Porsche", ['price'] = 1000, ['tipo'] = "work" },
	["ems_gs1200"] = { ['name'] = "Moto Policia", ['price'] = 1000, ['tipo'] = "work" },
	["scorcher"] = { ['name'] = "Policia Bicicleta", ['price'] = 1000, ['tipo'] = "work" },
	["policiabmwr1200"] = { ['name'] = "BMW R1200", ['price'] = 1000, ['tipo'] = "work" },
	["policiaheli"] = { ['name'] = "Policia Helicóptero", ['price'] = 1000, ['tipo'] = "work" },
	["fbi2"] = { ['name'] = "Granger SOG", ['price'] = 1000, ['tipo'] = "work" },
	["policeb"] = { ['name'] = "Harley Davidson", ['price'] = 1000, ['tipo'] = "work" },
	["riot"] = { ['name'] = "Blindado", ['price'] = 1000, ['tipo'] = "work" },
	["paramedicoambu"] = { ['name'] = "Ambulância", ['price'] = 1000, ['tipo'] = "work" },
	["ambulance"] = { ['name'] = "Ambulancia", ['price'] = 1000, ['tipo'] = "work" },
	["qrv"] = { ['name'] = "Explore", ['price'] = 1000, ['tipo'] = "work" },
	["hpsuv"] = { ['name'] = "SUV", ['price'] = 1000, ['tipo'] = "work" },
	["paramedicocharger2014"] = { ['name'] = "Dodge Charger 2014", ['price'] = 1000, ['tipo'] = "work" },
	["paramedicoheli"] = { ['name'] = "Paramédico Helicóptero", ['price'] = 1000, ['tipo'] = "work" },
	["seasparrow"] = { ['name'] = "Paramédico Helicóptero Água", ['price'] = 1000, ['tipo'] = "work" },
	["coach"] = { ['name'] = "Coach", ['price'] = 1000, ['tipo'] = "work" },
	["bus"] = { ['name'] = "Ônibus", ['price'] = 1000, ['tipo'] = "work" },
	["flatbed"] = { ['name'] = "Reboque", ['price'] = 1000, ['tipo'] = "work" },
	["towtruck"] = { ['name'] = "Towtruck", ['price'] = 1000, ['tipo'] = "work" },
	["towtruck2"] = { ['name'] = "Towtruck2", ['price'] = 1000, ['tipo'] = "work" },
	["ratloader"] = { ['name'] = "Caminhão", ['price'] = 1000, ['tipo'] = "work" },
	["ratloader2"] = { ['name'] = "Ratloader2", ['price'] = 1000, ['tipo'] = "work" },
	["rubble"] = { ['name'] = "Caminhão", ['price'] = 1000, ['tipo'] = "work" },
	["taxi"] = { ['name'] = "Taxi", ['price'] = 1000, ['tipo'] = "work" },
	["boxville4"] = { ['name'] = "Caminhão", ['price'] = 1000, ['tipo'] = "work" },
	["trash2"] = { ['name'] = "Caminhão", ['price'] = 1000, ['tipo'] = "work" },
	["tiptruck"] = { ['name'] = "Tiptruck", ['price'] = 1000, ['tipo'] = "work" },
	["scorcher"] = { ['name'] = "Scorcher", ['price'] = 1000, ['tipo'] = "work" },
	["mule3"] = { ['name'] = "Mule", ['price'] = 1000, ['tipo'] = "work" },
	["tribike"] = { ['name'] = "Tribike", ['price'] = 1000, ['tipo'] = "work" },
	["tribike2"] = { ['name'] = "Tribike2", ['price'] = 1000, ['tipo'] = "work" },
	["tribike3"] = { ['name'] = "Tribike3", ['price'] = 1000, ['tipo'] = "work" },
	["fixter"] = { ['name'] = "Fixter", ['price'] = 1000, ['tipo'] = "work" },
	["cruiser"] = { ['name'] = "Cruiser", ['price'] = 1000, ['tipo'] = "work" },
	["bmx"] = { ['name'] = "Bmx", ['price'] = 1000, ['tipo'] = "work" },
	["surfboard"] = { ['name'] = "Prancha de Surf", ['price'] = 1000, ['tipo'] = "work" },
	["dinghy"] = { ['name'] = "Dinghy", ['price'] = 1000, ['tipo'] = "work" },
	["jetmax"] = { ['name'] = "Jetmax", ['price'] = 1000, ['tipo'] = "work" },
	["marquis"] = { ['name'] = "Marquis", ['price'] = 1000, ['tipo'] = "work" },
	["seashark3"] = { ['name'] = "Seashark3", ['price'] = 1000, ['tipo'] = "work" },
	["speeder"] = { ['name'] = "Speeder", ['price'] = 1000, ['tipo'] = "work" },
	["speeder2"] = { ['name'] = "Speeder2", ['price'] = 1000, ['tipo'] = "work" },
	["squalo"] = { ['name'] = "Squalo", ['price'] = 1000, ['tipo'] = "work" },
	["suntrap"] = { ['name'] = "Suntrap", ['price'] = 1000, ['tipo'] = "work" },
	["toro"] = { ['name'] = "Toro", ['price'] = 1000, ['tipo'] = "work" },
	["toro2"] = { ['name'] = "Toro2", ['price'] = 1000, ['tipo'] = "work" },
	["tropic"] = { ['name'] = "Tropic", ['price'] = 1000, ['tipo'] = "work" },
	["tropic2"] = { ['name'] = "Tropic2", ['price'] = 1000, ['tipo'] = "work" },
	["phantom"] = { ['name'] = "Phantom", ['price'] = 1000, ['tipo'] = "work" },
	["packer"] = { ['name'] = "Packer", ['price'] = 1000, ['tipo'] = "work" },
	["supervolito"] = { ['name'] = "Supervolito", ['price'] = 1000, ['tipo'] = "work" },
	["supervolito2"] = { ['name'] = "Supervolito2", ['price'] = 1000, ['tipo'] = "work" },
	["cuban800"] = { ['name'] = "Cuban800", ['price'] = 1000, ['tipo'] = "work" },
	["mammatus"] = { ['name'] = "Mammatus", ['price'] = 1000, ['tipo'] = "work" },
	["vestra"] = { ['name'] = "Vestra", ['price'] = 1000, ['tipo'] = "work" },
	["velum2"] = { ['name'] = "Velum2", ['price'] = 1000, ['tipo'] = "work" },
	["buzzard2"] = { ['name'] = "Buzzard2", ['price'] = 1000, ['tipo'] = "work" },
	["frogger"] = { ['name'] = "Frogger", ['price'] = 1000, ['tipo'] = "work" },
	["maverick"] = { ['name'] = "Maverick", ['price'] = 1000, ['tipo'] = "work" },
	["tanker2"] = { ['name'] = "Gas", ['price'] = 1000, ['tipo'] = "work" },
	["armytanker"] = { ['name'] = "Diesel", ['price'] = 1000, ['tipo'] = "work" },
	["tvtrailer"] = { ['name'] = "Show", ['price'] = 1000, ['tipo'] = "work" },
	["trailerlogs"] = { ['name'] = "Woods", ['price'] = 1000, ['tipo'] = "work" },
	["tr4"] = { ['name'] = "Cars", ['price'] = 1000, ['tipo'] = "work" },
	["speedo"] = { ['name'] = "Speedo", ['price'] = 200000, ['tipo'] = "work" },
	["primo2"] = { ['name'] = "Primo2", ['price'] = 200000, ['tipo'] = "work" },
	["faction2"] = { ['name'] = "Faction2", ['price'] = 200000, ['tipo'] = "work" },
	["chino2"] = { ['name'] = "Chino2", ['price'] = 200000, ['tipo'] = "work" },
	["tornado5"] = { ['name'] = "Tornado5", ['price'] = 200000, ['tipo'] = "work" },
	["daemon"] = { ['name'] = "Daemon", ['price'] = 200000, ['tipo'] = "work" },
	["sanctus"] = { ['name'] = "Sanctus", ['price'] = 200000, ['tipo'] = "work" },
	["gburrito"] = { ['name'] = "GBurrito", ['price'] = 200000, ['tipo'] = "work" },
	["slamvan2"] = { ['name'] = "Slamvan2", ['price'] = 100000, ['tipo'] = "work" },
	["stafford"] = { ['name'] = "Stafford", ['price'] = 200000, ['tipo'] = "work" },
	["cog55"] = { ['name'] = "Cog55", ['price'] = 200000, ['tipo'] = "work" },
	["superd"] = { ['name'] = "Superd", ['price'] = 200000, ['tipo'] = "work" },
	["btype"] = { ['name'] = "Btype", ['price'] = 200000, ['tipo'] = "work" },
	["tractor2"] = { ['name'] = "Tractor2", ['price'] = 1000, ['tipo'] = "work" },
	["rebel"] = { ['name'] = "Rebel", ['price'] = 1000, ['tipo'] = "work" },
	["flatbed3"] = { ['name'] = "flatbed3", ['price'] = 1000, ['tipo'] = "work" },
	["volatus"] = { ['name'] = "Volatus", ['price'] = 1000000, ['tipo'] = "work" },
	["cargobob2"] = { ['name'] = "Cargo Bob", ['price'] = 1000000, ['tipo'] = "work" },		
	["dodgechargersrt"] = { ['name'] = "Dodge Charger SRT", ['price'] = 5400000, ['tipo'] = "import" },
	["audirs6"] = { ['name'] = "Audi RS6", ['price'] = 2800000, ['tipo'] = "import" },
	["bmwm3f80"] = { ['name'] = "BMW M3 F80", ['price'] = 2650000, ['tipo'] = "import" },
	["fordmustang"] = { ['name'] = "Ford Mustang", ['price'] = 3100000, ['tipo'] = "import" },
	["lancerevolution9"] = { ['name'] = "Lancer Evolution 9", ['price'] = 2600000, ['tipo'] = "import" },
	["lancerevolutionx"] = { ['name'] = "Lancer Evolution X", ['price'] = 2900000, ['tipo'] = "import" },
	["focusrs"] = { ['name'] = "Focus RS", ['price'] = 2400000, ['tipo'] = "import" },
	["mercedesa45"] = { ['name'] = "Mercedes A45", ['price'] = 2600000, ['tipo'] = "import" },
	["audirs7"] = { ['name'] = "Audi RS7", ['price'] = 3100000, ['tipo'] = "import" },
	["hondafk8"] = { ['name'] = "Honda FK8", ['price'] = 2900000, ['tipo'] = "import" },
	["mustangmach1"] = { ['name'] = "Mustang Mach 1", ['price'] = 3500000, ['tipo'] = "import" },
	["teslaprior"] = { ['name'] = "Tesla Prior", ['price'] = 3150000, ['tipo'] = "import" },		
	["m2"] = { ['name'] = "BMW M2", ['price'] = 3100000, ['tipo'] = "import" },
	["amarok"] = { ['name'] = "VW Amarok", ['price'] = 3300000, ['tipo'] = "import" },
	["bbentayga"] = { ['name'] = "Bentley Bentayga", ['price'] = 3600000, ['tipo'] = "import" },
	["evoque"] = { ['name'] = "Ranger Rover Evoque", ['price'] = 2500000, ['tipo'] = "import" },
	["xj6"] = { ['name'] = "XJ-6", ['price'] = 2600000, ['tipo'] = "import" },
	["btr04"] = { ['name'] = "Subaru Impreza STI 2006", ['price'] = 3500000, ['tipo'] = "import" },
	["z28"] = { ['name'] = "Camaro 2018 z 4.0", ['price'] = 3900000, ['tipo'] = "import" },
	["c7"] = { ['name'] = "Corvete C7 Stingray", ['price'] = 3900000, ['tipo'] = "import" },
	["mlnovitec"] = { ['name'] = "Maserati Levante Novitec", ['price'] = 4100000, ['tipo'] = "import" },
	["cx75"] = { ['name'] = "Jaguar cx75", ['price'] = 4200000, ['tipo'] = "import" },
	["dk350z"] = { ['name'] = "Nissan 350z", ['price'] = 6300000, ['tipo'] = "import" },
	["urus"] = { ['name'] = "Lamborghini Urus", ['price'] = 7700000, ['tipo'] = "import" },
	["sti"] = { ['name'] = "Subaru Impreza WRX STI Sedan 2011", ['price'] = 5200000, ['tipo'] = "import" },
	["sq72016"] = { ['name'] = "Audi SQ7", ['price'] = 5200000, ['tipo'] = "import" },
	["sbrwrx"] = { ['name'] = "Subaru Impreza Rally", ['price'] = 7200000, ['tipo'] = "import" },
	["spyker"] = { ['name'] = "Spyker", ['price'] = 5400000, ['tipo'] = "import" },
	["raptor2017"] = { ['name'] = "Ford Ranger Raptor", ['price'] = 4100000, ['tipo'] = "import" },
	["amggtr"] = { ['name'] = "Mercedez AMG GTR", ['price'] = 5300000, ['tipo'] = "import" },
	["nissan370z"] = { ['name'] = "Nissan 370z", ['price'] = 5300000, ['tipo'] = "import" },
	["fz07"] = { ['name'] = "Yamaha FZ", ['price'] = 520000, ['tipo'] = "import" },
	["charger"] = { ['name'] = "Dodge Charger 1995", ['price'] = 4300000, ['tipo'] = "import" },
	["moss"] = { ['name'] = "Mercedez Sls Amg Boss", ['price'] = 5100000, ['tipo'] = "import" },
	["hornet"] = { ['name'] = "Hornet", ['price'] = 2600000, ['tipo'] = "import" },
	["tiger"] = { ['name'] = "Tiger", ['price'] = 2800000, ['tipo'] = "import" },
	["terzo"] = { ['name'] = "Lamborghini Terzo", ['price'] = 9600000, ['tipo'] = "import" },
	["4c"] = { ['name'] = "Alfa Romeo 4C", ['price'] = 5500000, ['tipo'] = "import" },
	["99viper"] = { ['name'] = "Viper", ['price'] = 6200000, ['tipo'] = "import" },
	["ap2"] = { ['name'] = "ap2", ['price'] = 6200000, ['tipo'] = "import" },
	["contgt2011"] = { ['name'] = "contgt2011", ['price'] = 6200000, ['tipo'] = "import" },
	["mteche39"] = { ['name'] = "MTECHE39", ['price'] = 6200000, ['tipo'] = "import" },
	["rcf"] = { ['name'] = "rcf", ['price'] = 4200000, ['tipo'] = "import" },
	["rs5"] = { ['name'] = "Audi RS5", ['price'] = 4100000, ['tipo'] = "import" },
	["s600w220"] = { ['name'] = "s600w220", ['price'] = 6200000, ['tipo'] = "import" },
	["rs318"] = { ['name'] = "Audi RS3", ['price'] = 3400000, ['tipo'] = "import" },
	["amggt"] = { ['name'] = "Mercedez AMG GTR", ['price'] = 6400000, ['tipo'] = "import" },
	["f82"] = { ['name'] = "f82", ['price'] = 4400000, ['tipo'] = "import" },
	["cayenne"] = { ['name'] = "Porsche Cayenne", ['price'] = 8100000, ['tipo'] = "import" },
	["fx50s"] = { ['name'] = "fx50s", ['price'] = 4400000, ['tipo'] = "import" },
	["argiulia"] = { ['name'] = "argiulia", ['price'] = 2400000, ['tipo'] = "import" },
	["megaram"] = { ['name'] = "megaram", ['price'] = 2900000, ['tipo'] = "import" },
	["boss302"] = { ['name'] = "boss302", ['price'] = 2900000, ['tipo'] = "import" },
	["pana"] = { ['name'] = "pana", ['price'] = 2900000, ['tipo'] = "import" },
	["pg8"] = { ['name'] = "pg8", ['price'] = 2900000, ['tipo'] = "import" },
	["rrsport"] = { ['name'] = "rrsport", ['price'] = 2900000, ['tipo'] = "import" },
	["runner"] = { ['name'] = "runner", ['price'] = 2900000, ['tipo'] = "import" },
	["srt8"] = { ['name'] = "srt8", ['price'] = 2900000, ['tipo'] = "import" },
	["vapidlow"] = { ['name'] = "vapidlow", ['price'] = 2900000, ['tipo'] = "import" },
	["demon"] = { ['name'] = "demon", ['price'] = 2900000, ['tipo'] = "import" },
	["z28"] = { ['name'] = "z28", ['price'] = 2900000, ['tipo'] = "import" },
	["e63amg"] = { ['name'] = "e63amg", ['price'] = 2900000, ['tipo'] = "import" },
	["gt86"] = { ['name'] = "gt86", ['price'] = 2900000, ['tipo'] = "import" },
	["h1humm"] = { ['name'] = "h1humm", ['price'] = 2900000, ['tipo'] = "import" },
	["h6"] = { ['name'] = "h6", ['price'] = 2900000, ['tipo'] = "import" },
	["k5blzr"] = { ['name'] = "k5blzr", ['price'] = 2900000, ['tipo'] = "import" },
	["kodiak"] = { ['name'] = "kodiak", ['price'] = 2900000, ['tipo'] = "import" },
	["mfc"] = { ['name'] = "mfc", ['price'] = 2900000, ['tipo'] = "import" },
	["models"] = { ['name'] = "models", ['price'] = 2900000, ['tipo'] = "import" },
	["prius"] = { ['name'] = "prius", ['price'] = 2900000, ['tipo'] = "import" },
	["ram3500"] = { ['name'] = "ram3500", ['price'] = 2900000, ['tipo'] = "import" },
	["rx450h"] = { ['name'] = "rx450h", ['price'] = 2900000, ['tipo'] = "import" },
	["rrphantom"] = { ['name'] = "rrphantom", ['price'] = 2900000, ['tipo'] = "import" },
	["slsamg"] = { ['name'] = "slsamg", ['price'] = 2900000, ['tipo'] = "import" },
	["xt660"] = { ['name'] = "xt660", ['price'] = 2900000, ['tipo'] = "import" },
	["r1"] = { ['name'] = "Yamaha R1", ['price'] = 1000000, ['tipo'] = "exclusive" },	
	["bmws"] = { ['name'] = "BMW S1000 RR", ['price'] = 1000000, ['tipo'] = "exclusive" },
	["r1250"] = { ['name'] = "BMW GS R1250", ['price'] = 1000000, ['tipo'] = "exclusive" },
	["hcbr17"] = { ['name'] = "Honda CBR 1000", ['price'] = 1000000, ['tipo'] = "exclusive" },
	["hayabusa"] = { ['name'] = "Hayabusa", ['price'] = 1000000, ['tipo'] = "exclusive" },
	["z1000"] = { ['name'] = "Z1000", ['price'] = 1000000, ['tipo'] = "exclusive" },
	["cb500x"] = { ['name'] = "Honda CB500", ['price'] = 1000000, ['tipo'] = "exclusive" },
	["r6"] = { ['name'] = "Yamaha R6", ['price'] = 1000000, ['tipo'] = "import" },
	["zx10"] = { ['name'] = "Kawasaki ZX10R", ['price'] = 1000000, ['tipo'] = "exclusive" },	
	["dm1200"] = { ['name'] = "Ducati DM1200", ['price'] = 1000000, ['tipo'] = "exclusive" },
	["nh2r"] = { ['name'] = "Ninja NH2R", ['price'] = 1000000, ['tipo'] = "exclusive" },
	["shotaro"] = { ['name'] = "Shotaro", ['price'] = 1000000, ['tipo'] = "exclusive" },
	["stretch"] = { ['name'] = "Stretch", ['price'] = 1000000, ['tipo'] = "exclusive" },
	["phantom3"] = { ['name'] = "Phantom", ['price'] = 1000000, ['tipo'] = "exclusive" },
	["zr3802"] = { ['name'] = "ZR3802", ['price'] = 1000000, ['tipo'] = "exclusive" },
	["buzzard2"] = { ['name'] = "Buzzard2", ['price'] = 1000000, ['tipo'] = "exclusive" },
	["frogger"] = { ['name'] = "Frogger", ['price'] = 1000000, ['tipo'] = "exclusive" },
	["pbus2"] = { ['name'] = "Ônibus Festival", ['price'] = 1000000, ['tipo'] = "exclusive" },
	["monster4"] = { ['name'] = "Monster", ['price'] = 1000000, ['tipo'] = "exclusive" },
	["cargobob2"] = { ['name'] = "Cargo Bob", ['price'] = 1000000, ['tipo'] = "exclusive" },	
	["deathbike2"] = { ['name'] = "Death Bike", ['price'] = 1000000, ['tipo'] = "exclusive" },
	["sanctus"] = { ['name'] = "Sanctus", ['price'] = 1000000, ['tipo'] = "exclusive" },
	["f8t"] = { ['name'] = "Ferrari F8 Turbo", ['price'] = 1000000, ['tipo'] = "exclusive" },
	["p1"] = { ['name'] = "P1 GTR", ['price'] = 1000000, ['tipo'] = "exclusive" },
	["porsche930"] = { ['name'] = "Porsche 930", ['price'] = 1000000, ['tipo'] = "exclusive" },
	["na1"] = { ['name'] = "Honda NSX-R", ['price'] = 1000000, ['tipo'] = "exclusive" },
	["panamera17turbo"] = { ['name'] = "Porshce Panamera Turbo", ['price'] = 1000000, ['tipo'] = "exclusive" },
	["f458"] = { ['name'] = "Ferrari 458", ['price'] = 1000000, ['tipo'] = "exclusive" },
	["senna"] = { ['name'] = "MacLaren Senna", ['price'] = 1000000, ['tipo'] = "exclusive" },
	["divo"] = { ['name'] = "Bugatti Divo", ['price'] = 1000000, ['tipo'] = "exclusive" },
	["rmodsian"] = { ['name'] = "Lamborghini Sian", ['price'] = 1000000, ['tipo'] = "exclusive" },
	["lw458s"] = { ['name'] = "Ferrari 458 s", ['price'] = 1000000, ['tipo'] = "exclusive" },
	["kiagt"] = { ['name'] = "kiagt", ['price'] = 1000000, ['tipo'] = "exclusive" },
	["lp610"] = { ['name'] = "lp610", ['price'] = 1000000, ['tipo'] = "exclusive" },
	["rmodlp750"] = { ['name'] = "rmodlp750", ['price'] = 1000000, ['tipo'] = "exclusive" },
	["acs8"] = { ['name'] = "BMW i8", ['price'] = 1000000, ['tipo'] = "exclusive" },
	["ttrs"] = { ['name'] = "Audi TTS", ['price'] = 1000000, ['tipo'] = "exclusive" },
	["gtr"] = { ['name'] = "Nissan GTR", ['price'] = 1000000, ['tipo'] = "exclusive" },
	["bmwm4gts"] = { ['name'] = "BMW M4 GTS", ['price'] = 1000000, ['tipo'] = "exclusive" },
	["skyline"] = { ['name'] = "Nissan Skyline R34", ['price'] = 1000000, ['tipo'] = "exclusive" },
	["s15"] = { ['name'] = "Nissan Silvia S15", ['price'] = 1000000, ['tipo'] = "exclusive" },
	["vantage"] = { ['name'] = "Aston Martin Vantage", ['price'] = 1000000, ['tipo'] = "exclusive" },
	["celta"] = { ['name'] = "Celta Paredão", ['price'] = 1000000, ['tipo'] = "exclusive" },
	["veneno"] = { ['name'] = "Lamborghini Veneno", ['price'] = 1000000, ['tipo'] = "exclusive" },
	["agerars"] = { ['name'] = "Koenigsegg Agera RS", ['price'] = 1000000, ['tipo'] = "exclusive" },
	["msohs"] = { ['name'] = "Mclaren 688 HS", ['price'] = 1000000, ['tipo'] = "exclusive" },
	["19ftype"] = { ['name'] = "Jaguar F-Type", ['price'] = 1000000, ['tipo'] = "exclusive" },
	["nissantitan17"] = { ['name'] = "Nissan Titan 2017", ['price'] = 1000000, ['tipo'] = "exclusive" },
	["m6e63"] = { ['name'] = "BMW M6 E63", ['price'] = 1000000, ['tipo'] = "exclusive" },
	["180sx"] = { ['name'] = "Nissan 180SX", ['price'] = 1000000, ['tipo'] = "exclusive" },
	["filthynsx"] = { ['name'] = "Honda NSX", ['price'] = 1000000, ['tipo'] = "exclusive" },
	["lp700r"] = { ['name'] = "Lamborghini LP700R Conversível", ['price'] = 1000000, ['tipo'] = "exclusive" },
	["2013r8"] = { ['name'] = "Audi R8 PPI Razor", ['price'] = 1000000, ['tipo'] = "exclusive" },		
	["toyotasupra"] = { ['name'] = "Toyota Supra", ['price'] = 1000000, ['tipo'] = "exclusive" },		
	["w900"] = { ['name'] = "Kenworth W900", ['price'] = 1000000, ['tipo'] = "exclusive" },
	["cargobob"] = { ['name'] = "CSC Cargobob", ['price'] = 1000000, ['tipo'] = "exclusive" },
	["fc15"] = { ['name'] = "Ferrari fc15", ['price'] = 1000000, ['tipo'] = "exclusive" },
	["trophytruck"] = { ['name'] = "Trophytruck", ['price'] = 1000000, ['tipo'] = "exclusive" },
	["ferrariitalia"] = { ['name'] = "Ferrari Italia", ['price'] = 1000000, ['tipo'] = "exclusive" },
	["BALLTRUCK"] = { ['name'] = "Rola Bot", ['price'] = 1000000, ['tipo'] = "exclusive" },
	["supersport"] = { ['name'] = "Bugatti", ['price'] = 1000000, ['tipo'] = "exclusive" },
	["mazdarx7"] = { ['name'] = "Mazda RX-7", ['price'] = 1000000, ['tipo'] = "exclusive" },
	["zondab"] = { ['name'] = "Pagani Zonda Barchetta", ['price'] = 1000000, ['tipo'] = "exclusive" },
	["bugatti"] = { ['name'] = "Bugatti Veyron", ['price'] = 1000000, ['tipo'] = "exclusive" },
	["18performante"] = { ['name'] = "Lamborghini Huracan", ['price'] = 1000000, ['tipo'] = "exclusive" },
	["mst"] = { ['name'] = "Mustang", ['price'] = 1000000, ['tipo'] = "exclusive" },
}