fx_version 'bodacious'
game 'gta5'

ui_page 'nui/index.html'

client_scripts {
	'@vrp/lib/utils.lua',
	'client.lua'
}

server_scripts {
	'@vrp/lib/utils.lua',
	'server.lua'
}

files {
	'nui/index.html',
	
    'nui/css/bootstrap.min.css',
    'nui/css/jquery-ui.css',
	'nui/css/style.css',
	
    'nui/js/jquery-2.2.4.min.js',
    'nui/js/jquery-ui.min.js',
    'nui/js/ui.js',

	'nui/images/mochila.png',
	'nui/images/celular.png',
	'nui/images/radio.png',
	'nui/images/mascara.png',
	'nui/images/sapatos.png',
	'nui/images/chapeu.png',
	'nui/images/oculos.png',
	'nui/images/roupas.png',
	'nui/images/indentidade.png',
	'nui/images/colete.png',
	'nui/images/raceticket.png',
	'nui/images/militec.png',
	'nui/images/repairkit.png',

	'nui/images/dinheiro-sujo.png',
	'nui/images/capuz.png',
	'nui/images/algema.png',
	'nui/images/lockpick.png',
	'nui/images/placa.png',
	'nui/images/c4.png',
	'nui/images/placa.png',
	'nui/images/furadeira.png',
	'nui/images/serra.png',
	'nui/images/gatilho.png',
	'nui/images/pecadearma.png',

	'nui/images/armacaodefuradeira.png',
	'nui/images/armacaodeserra.png',
	'nui/images/broca.png',
	'nui/images/c4b.png',
	'nui/images/chaves.png',
	'nui/images/chave.png',
	'nui/images/controle.png',
	'nui/images/corda.png',
	'nui/images/disco.png',
	'nui/images/ferrob.png',
	'nui/images/ferro1.png',
	'nui/images/fios.png',
	'nui/images/fita.png',
	'nui/images/keycard.png',
	'nui/images/keycard2.png',
	'nui/images/masterpick.png',
	'nui/images/pano.png',
	'nui/images/pendrive2.png',
	'nui/images/pendrivebanco.png',

	'nui/images/gaze.png',
	'nui/images/atadura.png',
	'nui/images/antisseptico.png',
	'nui/images/kitmedico.png',

	'nui/images/engrenagem.png',
	'nui/images/ferramentas.png',
	'nui/images/estepe.png',
	'nui/images/vidro.png',
	'nui/images/macarico.png',

	'nui/images/agua.png',
	'nui/images/leite.png',
	'nui/images/cafe.png',
	'nui/images/cafecleite.png',
	'nui/images/cafeexpresso.png',
	'nui/images/capuccino.png',
	'nui/images/frappuccino.png',
	'nui/images/cha.png',
	'nui/images/icecha.png',
	'nui/images/sprunk.png',
	'nui/images/cola.png',
	'nui/images/energetico.png',

	'nui/images/pibwassen.png',
	'nui/images/tequilya.png',
	'nui/images/patriot.png',
	'nui/images/blarneys.png',
	'nui/images/jakeys.png',
	'nui/images/barracho.png',
	'nui/images/ragga.png',
	'nui/images/nogo.png',
	'nui/images/mount.png',
	'nui/images/cherenkov.png',
	'nui/images/bourgeoix.png',
	'nui/images/bleuterd.png',

	'nui/images/sanduiche.png',
	'nui/images/rosquinha.png',
	'nui/images/hotdog.png',
	'nui/images/xburguer.png',
	'nui/images/chips.png',
	'nui/images/batataf.png',
	'nui/images/pizza.png',
	'nui/images/frango.png',
	'nui/images/bcereal.png',
	'nui/images/bchocolate.png',
	'nui/images/taco.png',
	'nui/images/yakisoba.png',
	'nui/images/isca.png',
	"nui/images/dourado.png",
	"nui/images/corvina.png",
	"nui/images/salmao.png",
	"nui/images/pacu.png",
	"nui/images/pintado.png",
	"nui/images/pirarucu.png",
	"nui/images/tilapia.png",
	"nui/images/tucunare.png",
	"nui/images/lambari.png",

	'nui/images/xarelto.png',
	'nui/images/dipirona.png',
	'nui/images/tandrilax.png',
	'nui/images/dorflex.png',
	'nui/images/buscopan.png',
	'nui/images/nebacetin.png',
	'nui/images/hirudoid.png',

	'nui/images/r-xarelto.png',
	'nui/images/r-dipirona.png',
	'nui/images/r-tandrilax.png',
	'nui/images/r-dorflex.png',
	'nui/images/r-buscopan.png',
	'nui/images/r-nebacetin.png',
	'nui/images/hirudoid.png',

	'nui/images/meta-alta.png',
	'nui/images/meta-media.png',
	'nui/images/meta-baixa.png',

	'nui/images/composito-alta.png',
	'nui/images/composito-media.png',
	'nui/images/composito-baixa.png',

	'nui/images/nitrato-amonia.png',
	'nui/images/hidroxido-sodio.png',
	'nui/images/pseudoefedrina.png',
	'nui/images/eter.png',

	'nui/images/paraquedas.png',
	'nui/images/gasolina.png',
	'nui/images/sinalizador.png',
	'nui/images/extintor.png',

	'nui/images/tora.png',

	'nui/images/coca-alta.png',
	'nui/images/coca-baixa.png',
	'nui/images/coca-media.png',

	'nui/images/topazio.png',
	'nui/images/bronze.png',
	'nui/images/esmeralda.png',
	'nui/images/ouro.png',
	'nui/images/diamante.png',
	'nui/images/safira.png',
	'nui/images/ametista.png',
	'nui/images/ferro.png',
	'nui/images/rubi.png',

	'nui/images/faca.png',
	'nui/images/adaga.png',
	'nui/images/ingles.png',
	'nui/images/machete.png',
	'nui/images/canivete.png',
	'nui/images/grifo.png',
	'nui/images/golf.png',
	'nui/images/cabra.png',
	'nui/images/machado.png',
	'nui/images/lanterna.png',
	'nui/images/beisebol.png',
	'nui/images/garrafa.png',
	'nui/images/batalha.png',
	'nui/images/sinuca.png',
	'nui/images/pedra.png',
	'nui/images/cassetete.png',

	'nui/images/glock.png',
	'nui/images/magnum44.png',
	'nui/images/fiveseven.png',
	'nui/images/deserteagle.png',
	'nui/images/taser.png',
	'nui/images/specialcarbine.png',
	'nui/images/assaultsmg.png',
	'nui/images/advancedrifle.png',
	'nui/images/snspistol.png',

	'nui/images/m4a1.png',
	'nui/images/ak47.png',
	'nui/images/aks.png',

	'nui/images/mp5.png',
	'nui/images/uzi.png',

	'nui/images/remington.png',

	'nui/images/winchester22.png',

	'nui/images/municao.png',
	'nui/images/m-paraquedas.png',
	'nui/images/combustivel.png',
	'nui/images/m-sinalizador.png',
	'nui/images/m-extintor.png',
	'nui/images/m-glock.png',
	'nui/images/m-magnum44.png',
	'nui/images/m-fiveseven.png',
	'nui/images/m-deserteagle.png',
	'nui/images/m-taser.png',
	'nui/images/m-m4a1.png',
	'nui/images/m-ak47.png',
	'nui/images/m-aks.png',
	'nui/images/m-mp5.png',
	'nui/images/m-uzi.png',
	'nui/images/m-remington.png',
	'nui/images/m-winchester22.png',

	'nui/images/querosene.png',
	'nui/images/pasta-alta.png',
	'nui/images/pasta-media.png',
	'nui/images/pasta-baixa.png',
	'nui/images/folhas-coca.png',
	'nui/images/acido-sulfurico.png',
	'nui/images/calcio-po.png',

	'nui/images/corpo-magnum.png',
	'nui/images/corpo-glock.png',
	'nui/images/corpo-uzi.png',
	'nui/images/corpo-aks74u.png',
	'nui/images/corpo-ak47.png',
	'nui/images/molas.png',
	'nui/images/capsulas.png',
	'nui/images/kevlar.png',
	'nui/images/tecido.png',
	'nui/images/polvora.png',
	'nui/images/placa-metal.png',

	'nui/images/corpo-glock.png',
	'nui/images/corpo-magnum44.png',

	'nui/images/corpo-ak47.png',
	'nui/images/corpo-aks.png',

	'nui/images/corpo-uzi.png',


	'nui/GothamPro-Black.woff'
}